#!/bin/bash

skel_exists() {
    prog_exists skel
}

skel_wants() {
    [[ "${BEGINNING_PLATFORM}" == Linux ]] && echo linux-only-daemon
}

skel_start() {
    skel_status || rm -f /run/skel.pid
    skel &
    echo $! > /run/skel.pid
}

skel_reload() {
    skel --reload
}

skel_stop() {
    pidfilekill /run/skel.pid
    skel_status || rm -f /run/skel.pid
}

skel_status() {
    pidexists /run/skel.pid
}
