#!/bin/bash

BITLBEE_ARGS=${BITLBEE_ARGS:-}
BITLBEE_USER=${BITLBEE_USER:-}

bitlbee_exists() {
    prog_exists bitlbee
}

bitlbee_start() {
    if [[ "${BITLBEE_USER}" ]];then
        bitlbee -Fn ${BITLBEE_ARGS} ${BITLBEE_USER:+-u ${BITLBEE_USER}} >/dev/null 2>&1 &
    else
        bitlbee -Fn ${BITLBEE_ARGS} >/dev/null 2>&1 &
    fi
    echo $! > "@@runstatedir@@"/bitlbee.pid
}

bitlbee_stop() {
    pidfilekill "@@runstatedir@@"/bitlbee.pid
}

bitlbee_status() {
    pidfileexists "@@runstatedir@@"/bitlbee.pid
}
