#!/bin/bash

BLUEZ_ARGS=${BLUEZ_ARGS:-}

bluez_exists() {
    if prog_exists bluetoothd || PATH="@@libexecdir@@"/bluetooth:"@@bindir@@" prog_exists bluetoothd;then
        return 0
    else
        return 1
    fi
}

bluez_depends() {
    echo dbus dev
}

bluez_start() {
    PATH="@@libexecdir@@"/bluetooth:"@@bindir@@":"${PATH}"
    bluetoothd -n ${BLUEZ_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/bluetooth.pid
}

bluez_stop() {
    pidfilekill "@@runstatedir@@"/bluetooth.pid
}

bluez_status() {
    pidfileexists "@@runstatedir@@"/bluetooth.pid
}
