#!/bin/bash

busybox-syslogd_provides() {
    echo syslog
}

busybox-syslogd_depends() {
    [[ "${BEGINNING_PLATFORM}" == "Linux" ]] && echo busybox-klogd
}

busybox-syslogd_exists() {
    prog_exists busybox && busybox | grep -q syslogd
}

busybox-syslogd_start() {
    busybox syslogd -n ${BUSYBOX_SYSLOGD_CONF:+-f ${BUSYBOX_SYSLOGD_CONF}} ${BUSYBOX_SYSLOGD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/busybox-syslogd.pid
}

busybox-syslogd_stop() {
    pidfilekill "@@runstatedir@@"/busybox-syslogd.pid
}

busybox-syslogd_status() {
    pidfileexists "@@runstatedir@@"/busybox-syslogd.pid
}
