#!/bin/bash

CGMANAGER_ARGS=${CGMANAGER_ARGS:-}

cgmanager_exists() {
    prog_exists cgmanager
}

cgmanager_start() {
    cgmanager ${CGMANAGER_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/cgmanager.pid
}

cgmanager_stop() {
    pidfilekill "@@runstatedir@@"/cgmanager.pid
}

cgmanager_status() {
    pidfileexists "@@runstatedir@@"/cgmanager.pid
}

