#!/bin/bash

CONSOLEKIT_ARGS=${CONSOLEKIT_ARGS:-}

consolekit_exists() {
    prog_exists console-kit-daemon
}

consolekit_depends() {
    echo dbus
}

consolekit_wants() {
    [[ "${BEGINNING_PLATFORM}" == "Linux" ]] && echo cgmanager
}

consolekit_start() {
    console-kit-daemon ${CONSOLEKIT_ARGS} >/dev/null 2>&1
}

consolekit_stop() {
    pidfilekill "@@runstatedir@@"/console-kit-daemon.pid
}

consolekit_status() {
    pidfileexists "@@runstatedir@@"/console-kit-daemon.pid
}

