#!/bin/bash

CONSOLEFONT_FONT=${CONSOLEFONT_FONT:-}
CONSOLEFONT_MAP=${CONSOLEFONT_MAP:-}
CONSOLEFONT_UNIMAP=${CONSOLEFONT_UNIMAP:-}
CONSOLEFONT_SETFONT_ARGS=${CONSOLEFONT_SETFONT_ARGS:-}
CONSOLEFONT_VTERMS=${CONSOLEFONT_VTERMS:-}

consolefont_exists() {
    prog_exists setfont
}

consolefont_start() {
    consolefont_status
    [[ "${CONSOLEFONT_MAP}" ]] && CONSOLEFONT_SETFONT_ARGS="${CONSOLEFONT_SETFONT_ARGS} -m ${CONSOLEFONT_MAP}"
    [[ "${CONSOLEFONT_UNIMAP}" ]] && CONSOLEFONT_SETFONT_ARGS="${CONSOLEFONT_SETFONT_ARGS} -u ${CONSOLEFONT_UNIMAP}"
    local err tty
    for tty in $(for i in $(seq 1 ${CONSOLEFONT_VTERMS:-$GETTY_VTERMS});do echo /dev/tty${i};done);do
        if setfont -C "$tty" ${CONSOLEFONT_SETFONT_ARGS} ${CONSOLEFONT_FONT:+"${CONSOLEFONT_FONT}"} >/dev/null 2>&1;then
            err=$?
        elif [[ $? -eq 66 ]];then
            err=66
            BEGINNING_FAILURE="\"${CONSOLEFONT_FONT}\" does not exist"
            return $err
        else
            err=1
            return $err
        fi
    done
    echo "CONSOLEFONT_FONT=${CONSOLEFONT_FONT}"     > "@@runstatedir@@"/beginning/consolefont
    echo "CONSOLEFONT_MAP=${CONSOLEFONT_MAP}"       > "@@runstatedir@@"/beginning/consolefont
    echo "CONSOLEFONT_UNIMAP=${CONSOLEFONT_UNIMAP}" > "@@runstatedir@@"/beginning/consolefont
}

consolefont_stop() {
    local err tty
    for tty in $(for i in $(seq 1 ${VTERMS});do echo /dev/tty${i};done);do
        if setfont -C "$tty" >/dev/null 2>&1;then
            err=0
        else
            err=1
            return $err
        fi
    done
    rm -f "@@runstatedir@@"/beginning/consolefont
}

consolefont_status() {
    [[ -r "@@runstatedir@@"/beginning/consolefont ]]
}
