#!/bin/bash

# vixie-cron uses `cron`, cronie is `crond`, busybox uses links
cronie_exists() {
    prog_exists crond && ! prog_exists cron && [[ "$(readlink -f $(type -fPp crond))" != */busybox ]]
}

cronie_provides() {
    echo cron
}

cronie_start() {
    crond -n ${CRONIE_ARGS} &
    echo $! > "@@runstatedir@@"/cronie.pid
}

cronie_stop() {
    pidfilekill "@@runstatedir@@"/cronie.pid
}

cronie_status() {
    pidfileexists "@@runstatedir@@"/cronie.pid
}

