#!/bin/bash

# vixie-cron uses `cron`, cronie is `crond`
cronie_exists() {
    prog_exists crond && ! prog_exists cron && [[ "$(readlink -f $(type -fPp crond))" != */busybox ]]
}

cronie_provides() {
    echo cron
}

cronie_start() {
    crond -n ${CRONIE_ARGS} &
    echo $! > /run/cronie.pid
}

cronie_stop() {
    pidfilekill /run/cronie.pid
}

cronie_status() {
    pidfileexists /run/cronie.pid
}

