#!/bin/bash

CUPSD_ARGS=${CUPSD_ARGS:-}
CUPSD_CONF=${CUPSD_CONF:-"@@sysconfdir@@"/cups/cupsd.conf}

cupsd_exists() {
    prog_exists cupsd
}

cupsd_start() {
    cupsd -t -c ${CUPSD_CONF} ${CUPSD_ARGS} >/dev/null 2>&1 && \
    cupsd -f -c ${CUPSD_CONF} ${CUPSD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/cupsd.pid
}

cupsd_stop() {
    pidfilekill "@@runstatedir@@"/cupsd.pid
}

cupsd_status() {
    pidfileexists "@@runstatedir@@"/cupsd.pid
}
