#!/bin/bash

cupsd_exists() {
    prog_exists cupsd
}

cupsd_start() {
    cupsd -t -c ${CUPSD_CONFIG:-"@@sysconfdir@@"/cups/cupsd.conf} ${CUPSD_ARGS} >/dev/null 2>&1 && \
    cupsd -f -c ${CUPSD_CONFIG:-"@@sysconfdir@@"/cups/cupsd.conf} ${CUPSD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/cupsd.pid
}

cupsd_stop() {
    pidfilekill "@@runstatedir@@"/cupsd.pid
}

cupsd_status() {
    pidfileexists "@@runstatedir@@"/cupsd.pid
}
