#!/bin/bash

dbus_exists() {
    prog_exists dbus-daemon
}

dbus_start() {
    mkdir "@@runstatedir@@"/dbus >/dev/null 2>&1
    [[ -d "@@runstatedir@@"/dbus ]] || return 1
    dbus-uuidgen --ensure
    dbus-daemon --system --fork --nopidfile --print-pid ${DBUS_ARGS} > "@@runstatedir@@"/dbus.pid
}

dbus_reload() {
    dbus_status || return 1
    kill -1 $(<"@@runstatedir@@"/dbus.pid)
}

dbus_stop() {
    pidfilekill "@@runstatedir@@"/dbus.pid
}

dbus_status() {
    pidfileexists "@@runstatedir@@"/dbus.pid
}
