#!/bin/bash

DHCLIENT_ARGS=${DHCLIENT_ARGS:-}
DHCLIENT_CONF=${DHCLIENT_CONF:-}
DHCLIENT_IFACE=${DHCLIENT_IFACE:-}

dhclient_exists() {
    prog_exists dhclient
}

dhclient_provides() {
    echo network
}

dhclient_start() {
    dhclient -pf "@@runstatedir@@"/dhclient.pid -q ${DHCLIENT_CONF:+-cf ${DHCLIENT_CONF}} ${DHCLIENT_ARGS} ${DHCLIENT_IFACE} || return $?
}

dhclient_stop() {
    pidfilekill "@@runstatedir@@"/dhclient.pid
}

dhclient_status() {
    pidfileexists "@@runstatedir@@"/dhclient.pid
}
