#!/bin/bash

dhcpd_exists() {
    prog_exists dhcpd
}

dhcpd_start() {
    dhcpd -pf "@@runstatedir@@"/dhcpd.pid -q ${DHCPD_CONF:+-cf ${DHCPD_CONF}} ${DHCPD_ARGS} ${DHCPD_IFACE} || return $?
}

dhcpd_stop() {
    pidfilekill "@@runstatedir@@"/dhcpd.pid
}

dhcpd_status() {
    pidfileexists "@@runstatedir@@"/dhcpd.pid
}
