#!/bin/bash

haveged_exists() {
    prog_exists haveged
}

haveged_start() {
    haveged -p "@@runstatedir@@/haveged.pid" ${HAVEGED_ARGS}
}

haveged_stop() {
    pidfilekill "@@runstatedir@@"/haveged.pid
}

haveged_status() {
    pidfileexists "@@runstatedir@@"/haveged.pid
}

