#!/bin/bash

HOSTNAME=${HOSTNAME:-"localhost"}
[[ -s "@@sysconfdir@@"/hostname ]] && HOSTNAME=$(<"@@sysconfdir@@"/hostname)

hostname_exists() {
    prog_exists hostname || [[ -r "/proc/sys/kernel/hostname" ]]
}

hostname_lo_up() {
    if prog_exists ip;then
        ip link set dev lo up
    elif prog_exists ifconfig;then
        ifconfig lo up
    elif prog_exists busybox && busybox --list | grep -q ifconfig;then
        busybox ifconfig lo up
    else
        return 1
    fi
    return $?
}

hostname_lo_down() {
    if prog_exists ip;then
        ip link set dev lo down
    elif prog_exists ifconfig;then
        ifconfig lo down
    elif prog_exists busybox && busybox --list | grep -q ifconfig;then
        busybox ifconfig lo down
    else
        return 1
    fi
    return $?
}

hostname_lo_status() {
    if prog_exists ip;then
        ip link show lo | head -1 | grep -q 'UP'
    elif prog_exists ifconfig;then
        ifconfig lo | head -1 | grep -q 'UP'
    elif prog_exists busybox && busybox --list | grep -q ifconfig;then
        busybox ifconfig lo | head -1 | grep -q 'UP'
    else
        return 1
    fi
    return $?
}

hostname_start() {
    local err
    if prog_exists hostname;then
        hostname "${HOSTNAME}" || err=$?
    elif [[ -w "/proc/sys/kernel/hostname" ]];then
        echo "${HOSTNAME}" > /proc/sys/kernel/hostname || err=$?
    fi
    hostname_lo_up || err=$?
    [[ $err -eq 0 ]] && echo "${HOSTNAME}" > "@@runstatedir@@"/beginning/hostname
    return $err
}

hostname_stop() {
    hostname_lo_down
    return $?
}

hostname_status() {
    hostname_lo_status && [[ -r "@@runstatedir@@"/beginning/hostname ]]
}
