#!/bin/bash

HWCLOCK_ARGS=${HWCLOCK_ARGS:-}
HWCLOCK_TYPE=${HWCLOCK_TYPE:-UTC}
[[ -L "@@sysconfdir@@"/localtime && -r "@@sysconfdir@@"/localtime ]] && \
    HWCLOCK_TZ=$(realpath "@@sysconfdir@@"/localtime | cut -d'/' -f5-)
HWCLOCK_TZ=${HWCLOCK_TZ:-UTC}

hwclock_exists() {
    if prog_exists hwclock && [[ -e /dev/rtc0 ]];then
        return 0
    else
        return 1
    fi
}

hwclock_start() {
    local err
    export TZ=${HWCLOCK_TZ}
    case ${HWCLOCK_TYPE,,} in
        localtime)
            hwclock --hctosys --localtime ${HWCLOCK_ARGS};err=$?
        ;;
        utc)
            hwclock --hctosys --utc ${HWCLOCK_ARGS};err=$?
        ;;
        *)
            err=1
        ;;
    esac
    unset TZ
    echo "TZ=${HWCLOCK_TZ}" > "@@runstatedir@@"/beginning/hwclock
    return $err
}

hwclock_stop() {
    local err
    export TZ=${HWCLOCK_TZ}
    case ${HWCLOCK_TYPE,,} in
        localtime)
            hwclock --systohc --localtime;err=$?
        ;;
        utc)
            hwclock --systohc --utc;err=$?
        ;;
        *)
            err=1
        ;;
    esac
    unset TZ
    rm -f "@@runstatedir@@"/beginning/hwclock
    return $err
}

hwclock_status() {
    [[ -r "@@runstatedir@@"/beginning/hwclock ]]
}
