#!/bin/bash

lighttpd_exists() {
    prog_exists lighttpd
}

lighttpd_start() {
    lighttpd -t -f ${LIGHTTPD_CONFIG:-"@@sysconfdir@@"/lighttpd/lighttpd.conf} ${LIGHTTPD_ARGS} >/dev/null 2>&1 || return $?
    lighttpd -D -f ${LIGHTTPD_CONFIG:-"@@sysconfdir@@"/lighttpd/lighttpd.conf} ${LIGHTTPD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/beginning/lighttpd.pid
    pidfileexists "@@runstatedir@@"/beginning/lighttpd.pid || return 1
}

lighttpd_stop() {
    pidfilekill "@@runstatedir@@"/beginning/lighttpd.pid
}

lighttpd_status() {
    pidfileexists "@@runstatedir@@"/beginning/lighttpd.pid
}
