#!/bin/bash

OPENSSHD_ARGS=${OPENSSHD_ARGS:-}

opensshd_exists() {
    prog_exists sshd
}

opensshd_start() {
    [[ -x $(type -fPp sshd-keygen.sh 2>/dev/null) ]] && $(type -fPp sshd-keygen.sh 2>/dev/null)
    setsid -w $(type -fPp sshd 2>/dev/null) ${OPENSSHD_ARGS} >/dev/null 2>&1
}

opensshd_reload() {
    pidfilekill -HUP "@@runstatedir@@"/sshd.pid
}

opensshd_stop() {
    setsid -w kill $(<"@@runstatedir@@"/sshd.pid)
}

opensshd_status() {
    pidfileexists "@@runstatedir@@"/sshd.pid
}
