#!/bin/bash

openntpd_exists() {
    prog_exists openntpd
}

openntpd_depends() {
    echo network
}

openntpd_start() {
    openntpd -p "@@runstatedir@@"/openntpd.pid ${OPENNTPD_ARGS} >/dev/null 2>&1
}

openntpd_stop() {
    pidfilekill "@@runstatedir@@"/openntpd.pid
}

openntpd_status() {
    pidfileexists "@@runstatedir@@"/openntpd.pid
}
