#!/bin/bash

_redis_server() {
    pushd /var/db/redis >/dev/null 2>&1 || return $?
    su -s $(type -fPp sh) -c "redis-server ${REDIS_ARGS} $*" ${REDIS_USER}; local err=$?
    popd /var/db/redis >/dev/null 2>&1 || return $?
    return $err
}

redis_exists() {
    prog_exists redis-server
}

redis_start() {
    { cat "${REDIS_CONF}" && echo "daemonize yes" && echo "pidfile /run/redis.pid"; } \
        | redis-server - >/dev/null 2>&1
    return $?
}

redis_stop() {
    pidfilekill /run/redis.pid
}

redis_status() {
    pidfileexists /run/redis.pid
}

