#!/bin/bash

rsyslogd_provides() {
    echo syslog
}

rsyslogd_exists() {
    prog_exists rsyslogd
}

rsyslogd_start() {
    rsyslogd -n -i "@@runstatedir@@/rsyslogd.pid" ${RSYSLOGD_ARGS} >/dev/null 2>&1 &
}

rsyslogd_stop() {
    pidfilekill "@@runstatedir@@"/rsyslogd.pid
}

rsyslogd_status() {
    pidfileexists "@@runstatedir@@"/rsyslogd.pid
}
