#!/bin/bash

TOYBOX_SYSLOGD_ARGS=${TOYBOX_SYSLOGD_CONF:-}
TOYBOX_SYSLOGD_CONF=${TOYBOX_SYSLOGD_CONF:-}

toybox-syslogd_provides() {
    echo syslog
}

toybox-syslogd_depends() {
    [[ "${BEGINNING_PLATFORM}" == "Linux" ]] && echo toybox-klogd
}

toybox-syslogd_exists() {
    prog_exists toybox && toybox | grep -q syslogd
}

toybox-syslogd_start() {
    toybox syslogd -n ${TOYBOX_SYSLOGD_CONF:+-f ${TOYBOX_SYSLOGD_CONF}} ${TOYBOX_SYSLOGD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/toybox-syslogd.pid
}

toybox-syslogd_stop() {
    pidfilekill "@@runstatedir@@"/toybox-syslogd.pid
}

toybox-syslogd_status() {
    pidfileexists "@@runstatedir@@"/toybox-syslogd.pid
}
