#!/bin/bash

TOYBOX_KLOGD_ARGS=${TOYBOX_KLOGD_CONF:-}
TOYBOX_KLOGD_CONF=${TOYBOX_KLOGD_CONF:-}

toybox-klogd_provides() {
    echo klog
}

toybox-klogd_exists() {
    prog_exists toybox && toybox | grep -q klogd
}

toybox-klogd_start() {
    toybox klogd -n ${TOYBOX_KLOGD_CONF:+-f ${TOYBOX_KLOGD_CONF}} ${TOYBOX_KLOGD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/toybox-klogd.pid
}

toybox-klogd_stop() {
    pidfilekill "@@runstatedir@@"/toybox-klogd.pid
}

toybox-klogd_status() {
    pidfileexists "@@runstatedir@@"/toybox-klogd.pid
}
