#!/bin/bash

TRANSMISSION_ARGS=${TRANMISSION_ARGS:-}
TRANSMISSION_USER=${TRANSMISSION_USER:-"transmission"}

transmission_exists() {
    prog_exists transmission-daemon
}

transmission_start() {
    if [[ "${TRANSMISSION_USER}" ]];then
        touch "@@runstatedir@@"/transmission.pid && chown "${TRANSMISSION_USER}" "@@runstatedir@@"/transmission.pid
        su -s $(type -fPp sh) -c "transmission-daemon -x "@@runstatedir@@"/transmission.pid ${TRANSMISSION_ARGS}" "${TRANSMISSION_USER}" &
    else
        transmission-daemon -x "@@runstatedir@@"/transmission.pid ${TRANSMISSION_ARGS} &
    fi
}

transmission_stop() {
    pidfilekill "@@runstatedir@@"/transmission.pid
}

transmission_status() {
    pidfileexists "@@runstatedir@@"/transmission.pid
}
