#!/bin/bash

VDEVD_ARGS=${VDEVD_ARGS:-}
VDEVD_CONF=${VDEVD_CONF:-"@@sysconfdir@@"/vdev/vdevd.conf}
VDEVD_MOUNTPOINT=${VDEVD_MOUNTPOINT:-"/dev"}

vdevd_provides() {
    echo dev
}

vdevd_exists() {
    prog_exists vdevd
}

vdevd_start() {
    # suppress "Segmentation Fault" message from bash
    exec 2>/dev/null
    # vdevd is known to segfault even if the daemon starts and forks
    # successfully, so we run _status if $? ne 0 to make sure
    vdevd -c "${VDEVD_CONF}" -p "@@runstatedir@@"/vdevd.pid ${VDEVD_ARGS} ${VDEVD_MOUNTPOINT}
    vdevd_status; return $?
}

vdevd_stop() {
    pidfilekill "@@runstatedir@@"/vdevd.pid
}

vdevd_status() {
    pidfileexists "@@runstatedir@@"/vdevd.pid
}
