#!/bin/bash

# vixie-cron uses `cron`, cronie is `crond`, busybox uses links
vixie-cron_exists() {
    ! prog_exists crond && prog_exists cron && [[ "$(readlink -f $(type -fPp crontab))" != */busybox ]]
}

vixie-cron_provides() {
    echo cron
}

vixie-cron_start() {
    cron -n ${VIXIE_CRON_ARGS} &
    echo $! > "@@runstatedir@@"/vixie-cron.pid
}

vixie-cron_stop() {
    pidfilekill "@@runstatedir@@"/vixie-cron.pid
}

vixie-cron_status() {
    pidfileexists "@@runstatedir@@"/vixie-cron.pid
}

