#!/bin/bash

wicd_exists() {
    prog_exists wicd
}

wicd_provides() {
    echo network
}

wicd_depends() {
    echo dbus dev
}

wicd_start() {
    wicd --no-daemon ${WICD_ARGS} >/dev/null 2>&1 &
    echo $! > "@@runstatedir@@"/wicd.pid
}

wicd_stop() {
    pidfilekill "@@runstatedir@@"/wicd.pid
}

wicd_status() {
    pidfileexists "@@runstatedir@@"/wicd.pid
}
