#!/bin/bash

znc_exists() {
    prog_exists znc
}

znc_start() {
    if [[ "${ZNC_USER}" ]];then
        touch "@@runstatedir@@"/znc.pid && chown "${ZNC_USER}" "@@runstatedir@@"/znc.pid
        su -s $(type -fPp sh) -c "znc -f ${ZNC_ARGS}" "${ZNC_USER}" >/dev/null 2>&1 &
    else
        znc -f ${ZNC_ARGS} >/dev/null 2>&1 &
    fi
    echo $! > "@@runstatedir@@"/znc.pid
}

znc_stop() {
    pidfilekill "@@runstatedir@@"/znc.pid
}

znc_status() {
    pidfileexists "@@runstatedir@@"/znc.pid
}
