#!/bin/bash

avahi-daemon_start() {
    avahi-daemon_status || rm -f /run/avahi-daemon.pid
    avahi-daemon -s &
    echo $! > /run/avahi-daemon.pid
}

avahi-daemon_stop() {
    kill $(</run/avahi-daemon.pid)
    avahi-daemon_status || rm -f /run/avahi-daemon.pid
}

avahi-daemon_status() {
    avahi-daemon -c
}
