#!/bin/bash

bitlbee_exists() {
    prog_exists bitlbee
}

bitlbee_start() {
    bitlbee_status || rm -f /run/bitlbee.pid
    if [[ "${BITLBEE_USER}" ]];then
        touch /run/bitlbee.pid && chown "${BITLBEE_USER}" /run/bitlbee.pid
        su -s $(type -fPp sh) -c "bitlbee -n ${BITLBEE_ARGS}" "${BITLBEE_USER}" >/dev/null 2>&1 &
    else
        bitlbee -n ${BITLBEE_ARGS} >/dev/null 2>&1 &
    fi
    echo $! > /run/bitlbee.pid
}

bitlbee_stop() {
    pidfilekill /run/bitlbee.pid
    bitlbee_status || rm -f /run/bitlbee.pid
}

bitlbee_status() {
    pidfileexists /run/bitlbee.pid
}
