#!/bin/bash

bitlbee_exists() {
    prog_exists bitlbee
}

bitlbee_start() {
    bitlbee_status || rm -f /run/bitlbee.pid
    bitlbee -Fn ${BITLBEE_ARGS} >/dev/null 2>&1 &
    echo $! > /run/bitlbee.pid
}

bitlbee_stop() {
    pidfilekill /run/bitlbee.pid
    bitlbee_status || rm -f /run/bitlbee.pid
}

bitlbee_status() {
    pidfileexists /run/bitlbee.pid
}
