#!/bin/bash

bluez_exists() {
    if type -fPp bluetoothd || [[ -x /usr/libexec/bluetooth/bluetoothd ]];then
        return 0
    else
        return 1
    fi
}

bluez_depends() {
    echo dbus
}

bluez_start() {
    /usr/libexec/bluetooth/bluetoothd -n >/dev/null 2>&1 &
    echo $! > /run/bluetooth.pid
}

bluez_stop() {
    kill $(</run/bluetooth.pid)
    bluez_status || rm -f /run/bluetooth.pid
}

bluez_status() {
    pidexists /run/bluetooth.pid
}
