#!/bin/bash

bluez_depends() {
    echo dbus
}

bluez_start() {
    /usr/libexec/bluetooth/bluetoothd -n >/dev/null 2>&1 &
    echo $! > /run/bluetooth.pid
}

bluez_stop() {
    kill $(</run/bluetooth.pid)
    bluez_status || rm -f /run/bluetooth.pid
}

bluez_status() {
    pidexists /run/bluetooth.pid
}
