#!/bin/bash

busybox-syslog_provides() {
    echo syslog
}

busybox-syslog_depends() {
    [[ "${BEGINNING_PLATFORM}" == "Linux" ]] && echo busybox-klog
}

busybox-syslog_exists() {
    prog_exists busybox && busybox | grep -q syslogd
}

busybox-syslog_start() {
    busybox-syslog_status || rm -f /run/busybox-syslog.pid
    busybox syslogd -n ${BUSYBOX_SYSLOGD_CONF:+-f ${BUSYBOX_SYSLOGD_CONF}} ${BUSYBOX_SYSLOGD_ARGS} >/dev/null 2>&1 &
    echo $! > /run/busybox-syslog.pid
}

busybox-syslog_stop() {
    pidfilekill /run/busybox-syslog.pid
    busybox-syslog_status || rm -f /run/busybox-syslog.pid
}

busybox-syslog_status() {
    pidfileexists /run/busybox-syslog.pid
}
