#!/bin/bash

cgmanager_exists() {
    prog_exists cgmanager
}

cgmanager_start() {
    cgmanager_status || rm -f /run/cgmanager.pid
    cgmanager ${CGMANAGER_ARGS} >/dev/null 2>&1 &
    echo $! > /run/cgmanager.pid
    cgmanger_status; return $?
}

cgmanager_stop() {
    pidfilekill /run/cgmanager.pid
    cgmanager_status || rm -f /run/cgmanager.pid
}

cgmanager_status() {
    pidfileexists /run/cgmanager.pid
}

