#!/bin/bash

cgmanager_exists() {
    prog_exists cgmanager
}

cgmanager_start() {
    cgmanager ${CGMANAGER_ARGS} >/dev/null 2>&1 &
    echo $! > /run/cgmanager.pid
}

cgmanager_stop() {
    pidfilekill /run/cgmanager.pid
}

cgmanager_status() {
    pidfileexists /run/cgmanager.pid
}

