#!/bin/bash

connman_exists() {
    type -fPp connmand
}

connman_depends() {
    echo dbus
}

connman_start() {
    connman_status || rm -f /run/connmand.pid
    connmand -n >/dev/null 2>&1 &
    echo $! > /run/connman.pid
}

connman_stop() {
    kill $(</run/connman.pid)
    connman_status || rm -f /run/connman.pid
}

connman_status() {
    pidexists /run/connman.pid
}
