#!/bin/bash

connman_depends() {
    echo dbus
}

connman_start() {
    connmand -n >/dev/null 2>&1 &
    echo $! > /run/connman.pid
}

connman_stop() {
    kill $(</run/connman.pid)
    connman_status || rm -f /run/connman.pid
}

connman_status() {
    kill -0 $(</run/connman.pid) >/dev/null 2>&1; return $?
}
