#!/bin/bash

connman_exists() {
    prog_exists connmand
}

connman_provides() {
    echo network
}

connman_depends() {
    echo dbus dev
}

connman_start() {
    connman_status || rm -f /run/connman.pid
    connmand -n ${CONNMAN_ARGS} >/dev/null 2>&1 &
    echo $! > /run/connman.pid
}

connman_stop() {
    pidfilekill /run/connman.pid
    connman_status || rm -f /run/connman.pid
}

connman_status() {
    pidfileexists /run/connman.pid
}
