#!/bin/bash

consolefont_exists() {
    type -fPp setfont
}

consolefont_start() {
    consolefont_status
    [[ "${CONSOLEFONT_MAP}" ]] && CONSOLEFONT_SETFONT_ARGS="${CONSOLEFONT_SETFONT_ARGS} -m ${CONSOLEFONT_MAP}"
    [[ "${CONSOLEFONT_UNIMAP}" ]] && CONSOLEFONT_SETFONT_ARGS="${CONSOLEFONT_SETFONT_ARGS} -u ${CONSOLEFONT_UNIMAP}"
    local err tty
    for tty in $(for i in $(seq 1 ${VTERMS});do echo /dev/tty${i};done);do
        if setfont -C "$tty" ${CONSOLEFONT_SETFONT_ARGS} ${CONSOLEFONT_FONT:+"${CONSOLEFONT_FONT}"};then
            err=$?
        else
            err=1
            break
        fi
    done
    date +%s > /run/beginning/started.consolefont
    return $err
}

consolefont_stop() {
    local err tty
    for tty in $(for i in $(seq 1 ${VTERMS});do echo /dev/tty${i};done);do
        if setfont -C "$tty";then
            err=0
        else
            err=1
            break
        fi
    done
    rm -f /run/beginning/started.consolefont
    return $err
}

consolefont_status() {
    [[ -r /run/beginning/started.consolefont ]]
}
