#!/bin/bash

consolekit_depends() {
    echo dbus
}

consolekit_start() {
    consolekit_status || rm -f /run/consolekit.pid
    console-kit-daemon --no-daemon &
    echo $! > /run/consolekit.pid
}

consolekit_stop() {
    kill $(</run/consolekit.pid)
    consolekit_status || rm -f /run/consolekit.pid
}

consolekit_status() {
    pidexists $(</run/consolekit.pid)
}

