#!/bin/bash

consolekit_exists() {
    type -fPp console-kit-daemon
}

consolekit_depends() {
    echo dbus
}

consolekit_start() {
    consolekit_status || rm -f /run/console-kit-daemon.pid
    console-kit-daemon --no-daemon ${CONSOLEKIT_ARGS} >/dev/null 2>&1 &
}

consolekit_stop() {
    kill $(</run/console-kit-daemon.pid)
    consolekit_status || rm -f /run/console-kit-daemon.pid
}

consolekit_status() {
    pidexists /run/console-kit-daemon.pid
}

