#!/bin/bash

cronie_exists() {
    type -fPp crond
}

cronie_provides() {
    echo crond
}

cronie_start() {
    cronie_status || rm -f /run/cronie.pid
    crond -n "${CRONIE_ARGS}" &
    echo $! > /run/cronie.pid
}

cronie_stop() {
    kill $(</run/cronie.pid)
    cronie_status || rm -f /run/cronie.pid
}

cronie_status() {
    pidexists /run/cronie.pid
}

