#!/bin/bash

cups_exists() {
    prog_exists cupsd
}

cups_start() {
    cups_status || rm -f /run/cupsd.pid
    cupsd -t -c ${CUPSD_CONFIG:-/etc/cups/cupsd.conf} ${CUPSD_ARGS} >/dev/null 2>&1 && \
    cupsd -f -c ${CUPSD_CONFIG:-/etc/cups/cupsd.conf} ${CUPSD_ARGS} >/dev/null 2>&1 &
    echo $! > /run/cupsd.pid
}

cups_stop() {
    pidfilekill /run/cupsd.pid
    cups_status || rm -f /run/cupsd.pid
}

cups_status() {
    pidfileexists /run/cupsd.pid
}
