#!/bin/bash

cups-browsed_exists() {
    prog_exists cups-browsed
}

cups-browsed_depends() {
    echo cupsd avahi-daemon
}

cups-browsed_start() {
    cups-browsed --autoshutdown=avahi ${CUPS_BROWSED_ARGS} >/dev/null 2>&1 &
    echo $! > /run/cups-browsed.pid
}

cups-browsed_stop() {
    pidfilekill /run/cups-browsed.pid
}

cups-browsed_status() {
    pidfileexists /run/cups-browsed.pid
}
