#!/bin/bash

dbus_start() {
    dbus_status || rm -f /run/dbus.pid
    dbus-uuidgen --ensure
    dbus-daemon --system --fork
}

dbus_stop() {
    kill $(</run/dbus.pid)
    dbus_status || rm -f /run/dbus.pid
}

dbus_status() {
    pidexists $(</run/dbus.pid)
}
