#!/bin/bash

dbus_exists() {
    prog_exists dbus-daemon
}

dbus_start() {
    mkdir /run/dbus >/dev/null 2>&1
    [[ -d "/run/dbus" ]] || return 1
    dbus_status || rm -f /run/dbus.pid
    dbus-uuidgen --ensure
    dbus-daemon --system --fork --nopidfile --print-pid ${DBUS_ARGS} > /run/dbus.pid
}

dbus_reload() {
    dbus_status || return 1
    kill -1 $(</run/dbus.pid)
}

dbus_stop() {
    pidfilekill /run/dbus.pid
    dbus_status || rm -f /run/dbus.pid
}

dbus_status() {
    pidfileexists /run/dbus.pid
}
