#!/bin/bash

dhcpd_exists() {
    type -fPp dhcpd
}

dhcpd_start() {
    dhcpd_status || rm -f /run/dhcpd.pid
    dhcpd -pf /run/dhcpd.pid -q ${DHCPD_CONF:+-cf ${DHCPD_CONF}} ${DHCPD_ARGS} ${DHCPD_IFACE} || return $?
}

dhcpd_stop() {
    kill $(</run/dhcpd.pid)
    dhcpd_status || rm -f /run/dhcpd.pid
}

dhcpd_status() {
    pidfileexists /run/dhcpd.pid
}
