#!/bin/bash

getty_exists() {
    prog_exists agetty
}

getty_start() {
    if [[ "${BEGINNING_RUNNER}" == rc.init ]];then
        for (( i=1; i<=${GETTY_VTERMS}; i++ )); do
            sh -c "while true;do setsid agetty ${GETTY_ARGS} tty${i} linux;done" &>/dev/null &
        done
    else
        false
    fi
}

getty_reload() {
    agetty --reload
}

getty_stop() {
    # stopping login terminals is almost always a bad idea.
    # don't allow it. if it's not desired then the user should be
    # smart enough to remove it from CORE_DAEMONS
    [[ "$BEGINNING_RUNNER" == rc.shutdown ]] || return 0
    kill $(pgrep agetty) >/dev/null 2>&1
}

getty_status() {
    pgrep agetty >/dev/null 2>&1
}
