#!/bin/bash

haveged_exists() {
    type -fPp haveged
}

haveged_start() {
    haveged_status || rm -f /run/haveged.pid
    haveged -p "/run/haveged.pid" ${HAVEGED_ARGS}
}

haveged_stop() {
    pidfilekill /run/haveged.pid
    haveged_status || rm -f /run/haveged.pid
}

haveged_status() {
    pidfileexists /run/haveged.pid
}

