#!/bin/bash

hostname_exists() {
    type -fPp hostname
}

hostname_start() {
    hostname_status
    local err
    hostname "${HOSTNAME}"; err=$?
    [[ $err -eq 0 ]] && date +%s > /run/beginning/started.hostname
    return $err
}

hostname_stop() {
    if [[ "${BEGINNING_RUNNER}" == shutdown ]];then
        return 0
    else
        return 1
    fi
}

hostname_status() {
    [[ -r /run/beginning/started.hostname ]]
}
