#!/bin/bash

hostname_exists() {
    prog_exists hostname || [[ -r "/proc/sys/kernel/hostname" ]]
}

hostname_start() {
    hostname_status
    local err
    if [[ -w "/proc/sys/kernel/hostname" ]];then
        echo "${HOSTNAME}" > /proc/sys/kernel/hostname || err=$?
    else
        hostname "${HOSTNAME}" || err=$?
    fi
    [[ $err -eq 0 ]] && date +%s > /run/beginning/started.hostname
    return $err
}

hostname_stop() {
    if [[ "${BEGINNING_RUNNER}" == shutdown ]];then
        return 0
    else
        return 1
    fi
}

hostname_status() {
    [[ -r /run/beginning/started.hostname ]]
}
