#!/bin/bash

hostname_exists() {
    prog_exists hostname || [[ -r "/proc/sys/kernel/hostname" ]]
}

hostname_lo_up() {
    if prog_exists ip;then
        ip link set dev lo up
    elif prog_exists ifconfig;then
        ifconfig lo up
    else
        return 1
    fi
    return $?
}

hostname_lo_down() {
    if prog_exists ip;then
        ip link set dev lo down
    elif prog_exists ifconfig;then
        ifconfig lo down
    else
        return 1
    fi
    return $?
}

hostname_lo_status() {
    if prog_exists ip;then
        ip link show lo | head -1 | grep -q 'UP'
    elif prog_exists ifconfig;then
        ifconfig lo | head -1 | grep -q 'UP'
    else
        return 1
    fi
    return $?
}

hostname_start() {
    local err
    if [[ -w "/proc/sys/kernel/hostname" ]];then
        echo "${HOSTNAME}" > /proc/sys/kernel/hostname || err=$?
    else
        hostname "${HOSTNAME}" || err=$?
    fi
    hostname_lo_up || err=$?
    [[ $err -eq 0 ]] && echo "${HOSTNAME}" > /run/beginning/hostname
    return $err
}

hostname_stop() {
    hostname_status && rm /run/beginning/hostname
    hostname_lo_down
    return $?
}

hostname_status() {
    hostname_lo_status && [[ -r /run/beginning/hostname ]]
}
