#!/bin/bash

opensshd_exists() {
    type -fPp sshd
}

opensshd_start() {
    opensshd_status || rm -f /run/sshd.pid
    [[ -x $(type -fPp sshd-keygen.sh) ]] && $(type -fPp sshd-keygen.sh)
    setsid bash -c "$(type -fPp sshd)"
}

opensshd_reload() {
    setsid bash -c 'kill -HUP $(</run/sshd.pid)'
}

opensshd_stop() {
    setsid bash -c 'kill $(</run/sshd.pid)'
    opensshd_status || rm -f /run/sshd.pid
}

opensshd_status() {
    pidexists /run/sshd.pid
}
