#!/bin/bash

opensshd_exists() {
    type -fPp sshd
}

opensshd_start() {
    opensshd_status || rm -f /run/sshd.pid
    [[ -x $(type -fPp sshd-keygen.sh) ]] && $(type -fPp sshd-keygen.sh)
    setsid -w $(type -fPp sshd)
}

opensshd_reload() {
    kill -HUP $(</run/sshd.pid)
}

opensshd_stop() {
    setsid -w kill $(</run/sshd.pid)
    opensshd_status || rm -f /run/sshd.pid
}

opensshd_status() {
    pidexists /run/sshd.pid
}
