#!/bin/bash

openssh_exists() {
    prog_exists sshd
}

openssh_start() {
    openssh_status || rm -f /run/sshd.pid
    [[ -x $(type -fPp sshd-keygen.sh) ]] && $(type -fPp sshd-keygen.sh)
    setsid -w $(type -fPp sshd) ${OPENSSH_ARGS} >/dev/null 2>&1
}

openssh_reload() {
    pidfilekill -HUP /run/sshd.pid
}

openssh_stop() {
    setsid -w kill $(</run/sshd.pid)
    openssh_status || rm -f /run/sshd.pid
}

openssh_status() {
    pidfileexists /run/sshd.pid
}
