#!/bin/bash

RANDOMSEED_POOLSIZE=$(echo $(</proc/sys/kernel/random/poolsize) || echo 512)

randomseed_exists() {
    [[ -w /dev/urandom ]]
}

randomseed_start() {
    randomseed_status
    local err
    # read previous random state, then remove it
    if [[ -r "${RANDOMSEED_FILE}" ]];then
        cat "${RANDOMSEED_FILE}" > /dev/urandom || err=$?
        rm -f "${RANDOMSEED_FILE}"
    fi
    echo "RANDOMSEED_FILE=${RANDOMSEED_FILE}" > /run/beginning/randomseed
    echo "RANDOMSEED_POOLSIZE=${RANDOMSEED_POOLSIZE}" >> /run/beginning/randomseed
    return $err
}

randomseed_stop() {
    randomseed_status
    local err
    # save random state
    dd if=/dev/urandom of="${RANDOMSEED_FILE}" count=1 bs=${RANDOMSEED_POOLSIZE} >/dev/null 2>&1 || err=$?
    [[ "$err" -eq 0 ]] && rm -f /run/beginning/randomseed
    return $err
}

randomseed_status() {
    [[ -r /run/beginning/randomseed ]]
}
