#!/bin/bash

rsyslog_provides() {
    echo syslog
}

rsyslog_exists() {
    type -fPp rsyslogd
}

rsyslog_start() {
    rsyslog_status || rm -f /run/rsyslogd.pid
    rsyslogd -n -i "/run/rsyslogd.pid" ${RSYSLOG_ARGS} >/dev/null 2>&1 &
}

rsyslog_stop() {
    pidfilekill /run/rsyslogd.pid
    rsyslog_status || rm -f /run/rsyslogd.pid
}

rsyslog_status() {
    pidfileexists /run/rsyslogd.pid
}
