#!/bin/bash

rsyslog_start() {
    rsyslog_status || rm -f /run/rsyslog.pid
    rsyslogd -n >/dev/null 2>&1 &
    echo $! > /run/rsyslog.pid
}

rsyslog_stop() {
    kill $(</run/rsyslog.pid)
    rsyslog_status || rm -f /run/rsyslog.pid
}

rsyslog_status() {
    pidexists /run/rsyslog.pid
}
