#!/bin/bash

rsyslogd_provides() {
    echo syslog
}

rsyslogd_exists() {
    prog_exists rsyslogd
}

rsyslogd_start() {
    rsyslogd_status || rm -f /run/rsyslogd.pid
    rsyslogd -n -i "/run/rsyslogd.pid" ${RSYSLOGD_ARGS} >/dev/null 2>&1 &
}

rsyslogd_stop() {
    pidfilekill /run/rsyslogd.pid
    rsyslogd_status || rm -f /run/rsyslogd.pid
}

rsyslogd_status() {
    pidfileexists /run/rsyslogd.pid
}
