#!/bin/bash

skel_start() {
    skel_status || rm -f /run/skel.pid
    daemon &
    echo $! > /run/skel.pid
}

skel_stop() {
    kill $(</run/skel.pid)
    skel_status || rm -f /run/skel.pid
}

skel_status() {
    kill -0 $(</run/skel.pid) >/dev/null 2>&1; return $?
}
