#!/bin/bash

skel_exists() {
    type -fPp skel
}

skel_start() {
    skel_status || rm -f /run/skel.pid
    daemon &
    echo $! > /run/skel.pid
}

skel_stop() {
    kill $(</run/skel.pid)
    skel_status || rm -f /run/skel.pid
}

skel_status() {
    pidexists /run/skel.pid
}
