#!/bin/bash

transmission_exists() {
    type -fPp transmission-daemon
}

transmission_start() {
    transmission_status || rm -f /run/transmission.pid
    if [[ "${TRANSMISSION_USER}" ]];then
        touch /run/transmission.pid && chown "${TRANSMISSION_USER}" /run/transmission.pid
        su -s $(type -fPp sh) -c 'transmission-daemon -x /run/transmission.pid' "${TRANSMISSION_USER}" &
    else
        transmission-daemon -x /run/transmission.pid &
    fi
}

transmission_stop() {
    kill $(</run/transmission.pid)
    transmission_status || rm -f /run/transmission.pid
}

transmission_status() {
    pidexists /run/transmission.pid
}
